config/routes.rb
Rails.application.routes.draw do
  resources :communities
  resources :submissions
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'submissions#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :user
  has_many :submissions
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :user
  belongs_to :community
  has_one_attached :media

  validates :title, presence: true
  validates :body, length: { maximum:  8000 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_uniqueness_of :username
  validates_presence_of :username
  has_many :submissions, dependent: :destroy
  has_many :communities

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :find_communities

  def find_communities
    @communities = Community.all.order(title: :asc)
  end

  protected

    def configure_permitted_parameters
      added_attrs = [:username]
      devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
      devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
    end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /communities or /communities.json
  def index
    @communities = Community.all
  end

  # GET /communities/1 or /communities/1.json
  def show
  end

  # GET /communities/new
  def new
    @community = current_user.communities.build
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities or /communities.json
  def create
    @community = current_user.communities.build(community_params)

    respond_to do |format|
      if @community.save
        format.html { redirect_to community_url(@community), notice: "Community was successfully created." }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1 or /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to community_url(@community), notice: "Community was successfully updated." }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1 or /communities/1.json
  def destroy
    @community.destroy

    respond_to do |format|
      format.html { redirect_to communities_url, notice: "Community was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def community_params
      params.require(:community).permit(:name, :title, :description, :sidebar, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /submissions or /submissions.json
  def index
    @submissions = Submission.all
  end

  # GET /submissions/1 or /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions or /submissions.json
  def create
    @submission = Submission.new(submission_params)
    @submission.user_id = current_user.id

    respond_to do |format|
      if @submission.save
        format.html { redirect_to submission_url(@submission), notice: "Submission was successfully created." }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1 or /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to submission_url(@submission), notice: "Submission was successfully updated." }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1 or /submissions/1.json
  def destroy
    @submission.destroy

    respond_to do |format|
      format.html { redirect_to submissions_url, notice: "Submission was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def submission_params
      params.require(:submission).permit(:title, :body, :url, :media, :community_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_svg(name, options={})
    options[:title] ||= name.underscore.humanize
    options[:aria] ||= true
    options[:nocomment] ||= true
    options[:class] ||= options.fetch(:styles, "fill-current text-gray-500")
    filename = "#{name}.svg"
    inline_svg_tag(filename, options)
  end

  def author_of?(resource)
    user_signed_in? && current_user.id == resource.user_id
  end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/application/_basic_layout.html.erb
<div class="flex flex-wrap">
  <div class="w-full md:w-2/3 pr-0 md:pr-6 mb-6">
    <div class="bg-white shadow rounded p-8">
      <%= yield :primary_content %>
    </div>
  </div>
  <div class="w-full md:w-1/3">
    <div class="bg-white shadow px-8 pt-6 pb-8 rounded-sm">
      <%= yield :secondary_content %>
    </div>
  </div>
</div>

app/views/communities/_community.html.erb
<li id="<%= dom_id community %>" class="py-3">
  <p class="text-sm text-gray-600">w/<%= community.name %></p>
  <%= link_to community, class: "hover: text-indigo-600" do %>
    <h3 class="font-semibold"><%= community.title %></h3>
  <% end %>
  <div class="prose prose-indigo mb-4"><%= truncate(community.description, length: 140) %></div>
  <p class="text-xs text-gray-500">Last updated <%= community.updated_at.to_formatted_s(:nice) %></p>

  <% if author_of?(community) %>
    <div class="mt-6 flex items-center space-x-3">
      <%= link_to edit_community_path(community), class: "btn btn-white inline-flex items-center text-gray-600 text-sm" do %>
        <%= render_svg "icons/edit", styles: "w-4 h-4 fill-current text-gray-500 mr-2" %>
        Edit
      <% end %>

      <%= button_to community_path(community), method: :delete, class: "btn btn-white inline-flex items-center text-gray-600 text-sm group hover:text-red-600" do %>
        <%= render_svg "icons/delete", styles: "w-4 h-4 fill-current text-gray-500 mr-2 group-hover:text-red-600" %>
        Delete
      <% end %>
    </div>
  <% end %>
</li>

app/views/communities/_form.html.erb
<%= form_with(model: community) do |form| %>
  <% if community.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
        <% community.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :name %>
    <%= form.text_field :name, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :title %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :description %>
    <%= form.text_area :description, class: "input min-h-[140px]" %>
  </div>

  <div class="mb-6">
    <%= form.label :sidebar %>
    <%= form.text_area :sidebar, class: "input min-h-[140px]" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-indigo bg-indigo-500" %>
  </div>
<% end %>

app/views/communities/_sidebar.html.erb
<div class="rounded p-4">
  <div class="flex items-center justify-between pb-2 border-b mb-6">
    <div class="flex items-start flex-1">
      <%= render_svg "icons/conversation", styles: "w-4 fill-current text-indigo-600 mr-2 mt-1" %>
      <div>
        <h1 class="font-mono text-sm leading-tight">w/<%= community.name %></h1>
        <h3 class="font-bold text-2xl leading-tight"><%= community.title %></h3>
      </div>
    </div>

    <% if author_of?(community) %>
      <%= link_to "Edit", edit_community_path(community), class: "underline text-indigo-600 hover:no-underline" %>
    <% end %>
  </div>

  <div class="grid grid-cols-2 gap-3 mb-6">
    <div>
      <p><%= "Submission".pluralize(community.submissions.size) %></p>
      <p class="font-bold text-2xl"><%= community.submissions.size %></p>
    </div>
    <div>
      <p><%= "Subscriber".pluralize(community.submissions.size) %></p>
      <p class="font-bold text-2xl">0</p>
    </div>
  </div>
  <hr class="mb-6">

  <div>
    <p>Description</p>
    <div class="prose prose-indigo my-3"><%= community.description %></div>
  </div>

  <hr class="mb-6">

  <div>
    <p>Sidebar</p>
    <div class="prose prose-indigo my-3"><%= community.sidebar %></div>
  </div>
</div>

app/views/communities/edit.html.erb
<% content_for :community_label, "Edit Community" %>

<% content_for :primary_content do %>
  <h1 class="font-bold text-3xl mb-6">Edit community</h1>
  <%= render 'form', community: @community %>
<% end %>

<% content_for :secondary_content do %>
  <div class="p-4">
    <%= render_svg "community", style: " h-auto mb-4" %>

    <h3 class="font-bold">Edit the <%= @community.name %> community on webbit</h3>

    <p class="text-sm italic">Each community requires the following: </p>

    <ul class="mt-4 list-disc pl-6 leading-loose">
      <li>Name</li>
      <li>Title</li>
      <li>Description</li>
    </ul>

  </div>
<% end %>

<%= render "application/basic_layout" %>

app/views/communities/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :primary_content do %>
  <% if @communities.any? %>
    <h1 class="text-3xl font-bold mb-6">Communities</h1>
    <ul class="divide-y" id="communities">
      <% @communities.each do |community| %>
        <%= render community %>
      <% end %>
    </ul>
  <% else %>
    <div class="p-10 text-center">
      <div class="flex justify-center mb-3">
        <%= render_svg "icons/empty" %>
      </div>
      <p class="mb-4">Wow so empty...</p>
      <%= link_to "Create a new community", new_community_path, class: "btn btn-indigo" %>
    </div>
  <% end %>
<% end %>

<% content_for :secondary_content do %>
  <%= link_to "New community", new_community_path, class: "btn btn-indigo" %>
<% end %>



<%= render "basic_layout" %>

app/views/communities/new.html.erb
<% content_for :community_label, "Create Community" %>

<% content_for :primary_content do %>
  <h1 class="font-bold text-3xl mb-6">Create a community</h1>
  <%= render 'form', community: @community %>
<% end %>

<% content_for :secondary_content do %>
  <div class="p-4">
    <%= render_svg "community", style: " h-auto mb-4" %>
    <h3 class="font-bold">Create a new community on webbit</h3>
    <p class="text-sm italic">Each community requires the following: </p>
    <ul class="mt-4 list-disc pl-6 leading-loose">
      <li>Name</li>
      <li>Title</li>
      <li>Description</li>
    </ul>
  </div>
<% end %>

<%= render "application/basic_layout" %>

app/views/communities/show.html.erb
<% content_for :community_label, "w/#{@community.name}" %>

<% content_for :primary_content do %>
  <% @community.submissions.each do |submission| %>
    <%= render "submissions/submission", submission: submission %>
  <% end %>
<% end %>

<% content_for :secondary_content do %>
  <%= render "sidebar", community: @community %>
<% end %>

<%= render "application/basic_layout" %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<h1 class="text-3xl font-bold underline text-red-400">
  Hello world!
</h1>

app/views/layouts/admin.html.erb
<h1>Admin</h1>

<%= debug params %>

<%= yield %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webbit</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body class="bg-gray-200 relative h-screen overflow-x-hidden accent-indigo-600">

<% flash.each do |type, message| %>
  <% if type == 'alert' %>
    <div class="bg-red-500">
      <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans">
        <%= message %>
      </div>
    </div>
  <% elsif type == 'notice' %>
    <div class="bg-green-500">
      <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans">
        <%= message %>
      </div>
    </div>
  <% end %>
<% end %>

<nav class="bg-white py-2 border-b border-gray-400" role="navigation" aria-label="main navigation">
  <div class="flex flex-wrap items-center justify-center lg:justify-start lg:content-center px-4 lg:px-6 lg:space-x-3 lg:py-0 py-3">
    <%= link_to root_path, class: "leading-normal no-underline text-gray-800 my-2 md:my-0 hover:text-indigo-600 lg:w-auto w-full lg:text-left text-center" do %>
      <h1 class="text-lg pr-2 uppercase font-semibold">Webbit</h1>
    <% end %>

    <div class="flex flex-wrap justify-start w-full lg:w-2/3 flex-1">

      <div class="flex flex-wrap items-center lg:flex-1 lg:space-x-6 lg:w-auto w-full">
        <% if @communities.any? %>
          <div class="lg:w-1/4 w-full lg:mb-0 mb-3">
            <div data-controller="dropdown" class="rounded bg-white text-gray-700 ml-1 hover:bg-gray-50 relative">
              <%= link_to "", class: "border no-underline flex items-center justify-between text-gray-700 py-3 px-3 rounded border-gray-400", data: {action: "click->dropdown#toggle click->@window->dropdown#hide"} do %>
                <span class="font-semibold text-sm"><%= content_for?(:community_label) ? yield(:community_label) : "Select a community" %></span>
                <div class="pointer-events-none absolute right-2 inset-y-5 flex items-center">
                  <%= render_svg "icons/chevron-down", styles: "fill-current w-5 h-5 text-gray-500" %>
                </div>
              <% end %>
              <ul class="hidden absolute top-10 left-0 bg-white min-w-[250px] border border-gray-400 rounded shadow-lg divide-y" data-dropdown-target="menu">
                <% @communities.each do |community| %>
                  <li>
                    <%= link_to community, class: "bg-white rounded px-4 py-2 hover:bg-indigo-50 hover:text-indigo-700 flex items-center group" do %>
                      <%= render_svg "icons/conversation", styles: "mr-2 fill-current text-gray-500 w-4 h-4 group-hover:text-indigo-600" %>
                      <span>w/</span><%= community.name %>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </div>

          </div>
        <% end %>

        <div class="lg:flex-1 lg:w-auto w-full lg:mb-0 mb-3">
          <div class="relative">
            <input type="text" class="input pl-9" placeholder="Search webbit">
            <div class="pointer-events-none absolute inset-y-5 left-2 flex items-center">
              <%= render_svg "icons/search", styles: "stroke-current w-6 h-6 text-gray-400" %>
            </div>
          </div>
        </div>

      </div>

      <div class="lg:pl-4 flex flex-wrap items-center justify-end pt-4 lg:pt-0">
        <div class="mr-3">
          <% if user_signed_in? %>
            <%= link_to new_submission_path, class: "p-4 rounded hover:bg-indigo-50 bg-white block" do %>
              <%= render_svg "icons/create", styles: "group-hover:text-indigo-600 fill-current text-gray-600", title: "Create submission" %>
            <% end %>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "btn btn-outline mr-4" %>
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-indigo" %>
          <% end %>
        </div>
        <% if user_signed_in? %>
          <div data-controller="dropdown" class="rounded bg-white border border-gray-400 text-gray-600 ml-1 hover:bg-gray-100 py-0 px-4">
              <%= link_to "#", class: "no-underline flex justify-between text-sm tracking-wide items-center font-semibold select-none py-3", data: { action: "click->dropdown#toggle click@window->dropdown#hide" } do %>
                <%= current_user.username ||= current_user.email %>
                <%= render_svg "icons/chevron-down", styles: "ml-2 w-4 h-4 text-gray-600" %>
              <% end %>
              <div class="relative">
                <ul class="hidden absolute top-2 right-4 bg-white min-w-[200px] border border-gray-400 rounded shadow-lg" data-dropdown-target="menu">
                  <li>
                    <%= link_to "#", class: "hover:bg-indigo-600 hover:text-white text-gray-700 no-underline block py-3 px-4 flex items-center text-sm group" do %>
                      <%= render_svg "icons/user", styles: "w-4 h-4 fill-current group-hover:text-white text-gray-600 mr-3" %>
                      My profile
                    <% end %>
                  </li>
                  <li>
                    <%= link_to edit_user_registration_path, class: "hover:bg-indigo-600 hover:text-white text-gray-700 no-underline block py-3 px-4 flex items-center text-sm group" do %>
                      <%= render_svg "icons/settings", styles: "w-5 h-5 fill-current text-gray-600 mr-3 group-hover:text-white" %>
                      Account settings
                    <% end %>
                  </li>
                  <li>
                    <%= button_to destroy_user_session_path, method: :delete, class: "hover:bg-indigo-600 hover:text-white text-gray-700 no-underline block py-3 px-4 flex items-center text-sm group w-full" do %>
                      <%= render_svg "icons/signout", styles: "w-5 h-5 fill-current text-gray-600 mr-3 group-hover:text-white" %>
                      Sign out
                    <% end %>
                  </li>
                </ul>
              </div>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</nav>

<div class="container mx-auto py-6 lg:px-6 px-4">
  <%= yield %>
</div>
</body>
</html>

app/views/submissions/_form.html.erb
<div data-controller="tabs">
  <%= form_with(model: submission) do |form| %>
    <% if submission.errors.any? %>
      <div class="bg-red-50 text-red-700 p-4 rounded-border border-red-300 mb-6">
        <h2 class="leading-tight font-bold mb-3">
          <%= pluralize(submission.errors.count, "error") %>
          prohibited this submission from being saved:
        </h2>
        <ul>
          <% submission.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%#= form.hidden_field :user_id, value: current_user.id %>

    <div class="mb-6 w-full lg:w-2/5">
      <label for="#">Community</label>
      <div class="relative">
        <%= form.select :community_id, Community.all.collect{ |c| [c.name, c.id]}, {prompt: "Choose a community"}, {class: "select"} %>
        <div class="pointer-events-none absolute inset-y-5 right-2 flex items-center">
          <%= render_svg "icons/chevron-down", styles: "fill-current w-4 h-4 text-gray-500" %>
        </div>
      </div>
    </div>

    <label for="submission_type">Submission Type</label>
    <nav role="submission type" class="mb-6">
      <ul class="lg:divide-x divide-y grid grid-cols-1 lg:grid-cols-3 gap-0 border rounded shadow-sm">
        <li>
          <a href="#" data-action="click->tabs#toggle" data-tabs-target="button" data-tab-id="text" class="p-4 flex items-center justify-center group hover:text-indigo-600">
            <%= render_svg "icons/text", styles: "group-hover:text-indigo-600 text-gray-500 w-5 h-5 fill-current mr-2" %>
            Text
          </a>
        </li>
        <li>
          <a href="#" data-action="click->tabs#toggle" data-tabs-target="button" data-tab-id="url" class="p-4 flex items-center justify-center group hover:text-indigo-600">
            <%= render_svg "icons/link", styles: "group-hover:text-indigo-600 text-gray-500 w-5 h-5 fill-current mr-2" %>
            URL
          </a>
        </li>
        <li>
          <a href="#" data-action="click->tabs#toggle" data-tabs-target="button" data-tab-id="media" class="p-4 flex items-center justify-center group hover:text-indigo-600">
            <%= render_svg "icons/image", styles: "group-hover:text-indigo-600 text-gray-500 w-5 h-5 fill-current mr-2" %>
            Image or video
          </a>
        </li>
      </ul>
    </nav>


      <div class="mb-6">
        <%= form.label :title %>
        <%= form.text_field :title, class: "input" %>
      </div>

      <div class="mb-6" data-tabs-target="text">
        <%= form.label :body %>
        <%= form.text_area :body, class: "input min-h-[200px]" %>
      </div>


    <div data-tabs-target="url" class="mb-6 hidden">
      <%= form.label :url %>
      <%= form.text_field :url, class: "input" %>
    </div>

    <div class="hidden mb-6" data-tabs-target="media">
      <%= form.label :media do %>
        <span class="mb-1 inline-block">Attach a video or image</span>
        <%= form.file_field :media, class: "block w-full text-sm text-gray-500
      file:mr-4 file:py-2 file:px-4
      file:rounded-full file:border-0
      file:text-sm file:font-semibold
      file:bg-indigo-50 file:text-indigo-700
      hover:file:bg-indigo-100" %>
      <% end %>
    </div>

    <div>
      <%= form.submit class: "btn btn-indigo bg-indigo-600" %>
    </div>
  <% end %>
</div>

app/views/submissions/_guidelines.html.erb
<h3 class="font-bold text-xl mb-4">Posting to Webbit</h3>
<ol class="list-none leading-loose p-0 text-sm divide-y">
  <li class="py-1">Remember to be human</li>
  <li class="py-1">Behave like you would in real life</li>
  <li class="py-1">Look for the original source of content</li>
  <li class="py-1">Search for duplicates before posting</li>
  <li class="py-1">Read the community's news</li>
</ol>

app/views/submissions/_submission.html.erb
<li id="<%= dom_id submission %>">
  <div class="py-3 flex items-start flex-wrap">
    <% if submission.media.attached? %>
      <div class="w-2/12">
        <%= link_to submission do %>
          <% if submission.media.video? %>
            <%= video_tag submission.media %>
          <% else %>
            <%= image_tag submission.media, alt: submission.title, class: "rounded shadow-lg" %>
          <% end %>
        <% end %>
      </div>
    <% end %>


    <div class="flex-1 <%= 'pl-4' if submission.media.attached? %>">
      <h3 class="mb-1 flex flex-wrap font-semibold items-center text-xl hover:text-indigo-600">
        <%= link_to submission.title, submission, class: "no-underline" %>
        <% if submission.url? %>
        <span class="pl-2 text-xs font-normal font-mono text-indigo-400 tracking-tighter">
          <%= truncate(submission.url, length: 18) %>
        </span>
        <% end %>
      </h3>

      <% if submission.body? %>
        <div class="text-base text-gray-700">
          <%= truncate(submission.body, length: 140) %>
        </div>
      <% end %>

      <% if user_signed_in? && current_user.id == submission.user_id %>
        <div class="pt-4 flex flex-wrap items-center">
          <%= link_to edit_submission_path(submission), class: "no-underline mr-2" do %>
            <%= render_svg "icons/edit", title: "Edit", styles: "fill-current text-gray-400 w-5 h-5 hover:text-indigo-600" %>
          <% end %>

          <%= link_to submission_path(submission), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this submission?"}, class: "no-underline mr-2" do %>
            <%= render_svg "icons/delete", title: "Edit", styles: "fill-current text-gray-400 w-5 h-5 hover:text-indigo-600" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</li>

app/views/submissions/edit.html.erb
<% content_for :community_label, "Edit submission" %>

<% content_for :primary_content do %>
  <h1 class="text-3xl font-bold mb-6">Editing submission</h1>
  <%= render "form", submission: @submission %>
<% end %>

<% content_for :secondary_content do %>
  <%= render "guidelines" %>
<% end %>

<%= render "application/basic_layout" %>

app/views/submissions/index.html.erb
<% content_for :primary_content do %>

  <% if @submissions.any? %>
    <div id="submissions">
      <ul class="divide-y">
        <% @submissions.each do |submission| %>
          <%= render submission %>
        <% end %>
      </ul>
    </div>
  <% else %>
    <div class="p-10 text-center">
      <div class="flex justify-center mb-3">
        <%= render_svg "icons/empty" %>
      </div>
      <p class="mb-4">Wow so empty...</p>
      <%= link_to "Create a new post", new_submission_path, class: "btn btn-indigo" %>
    </div>
  <% end %>
<% end %>

<% content_for :secondary_content do %>
  <div class="mb-6">
  <%= link_to "New submission", new_submission_path, class: "btn btn-indigo block text-center" %>
  </div>
  <div>
  <%= link_to "New community", new_community_path, class: "btn btn-white block text-center" %>
  </div>
<% end %>

<%= render "application/basic_layout" %>

app/views/submissions/new.html.erb
<% content_for :community_label, "Create submission" %>

<% content_for :primary_content do %>
  <h1 class="text-3xl font-bold mb-6">New submission</h1>
  <%= render "form", submission: @submission %>
<% end %>

<% content_for :secondary_content do %>
  <%= render "guidelines" %>
<% end %>

<%= render "application/basic_layout" %>

app/views/submissions/show.html.erb
<% content_for :community_label, "w/#{@submission.community.name}" %>

<%= render @submission %>

<div>
  <%= link_to "Edit this submission", edit_submission_path(@submission) %> |
  <%= link_to "Back to submissions", submissions_path %>

  <%= button_to "Destroy this submission", @submission, method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete this submission?" } } %>
</div>